import type {
  DiscrepancyRecord,
  ExceptionRecord,
  SystemConfigRecord,
  SyncJobRecord,
} from '@/lib/types';

export const systemConfigs: SystemConfigRecord[] = [
  {
    id: 'cfg-1',
    systemType: 'itop',
    name: 'iTop CMDB',
    url: 'https://itop.example.local',
    username: 'auditbot',
    secretMasked: '••••••••',
    enabled: true,
    lastCheckedAt: '2026-03-27T05:20:00Z',
  },
  {
    id: 'cfg-2',
    systemType: 'vcenter',
    name: 'vCenter PROD-01',
    url: 'https://vcenter01.example.local',
    username: 'administrator@vsphere.local',
    secretMasked: '••••••••',
    enabled: true,
    lastCheckedAt: '2026-03-27T05:20:00Z',
  },
  {
    id: 'cfg-3',
    systemType: 'unity',
    name: 'Dell Unity 600',
    url: 'https://unity600.example.local',
    username: 'svc-audit',
    secretMasked: '••••••••',
    enabled: true,
    lastCheckedAt: '2026-03-27T05:20:00Z',
  },
  {
    id: 'cfg-4',
    systemType: 'pure',
    name: 'Pure Storage 01',
    url: 'https://pure01.example.local',
    username: 'pure-api',
    secretMasked: 'token-••••',
    enabled: false,
    lastCheckedAt: '2026-03-26T22:10:00Z',
  },
];

export const syncJobs: SyncJobRecord[] = [
  {
    id: 'job-1042',
    startedAt: '2026-03-27T05:18:00Z',
    finishedAt: '2026-03-27T05:21:40Z',
    status: 'success',
    totalSources: 5,
    succeededSources: 5,
    discrepancies: 18,
    note: 'Full sync completed with exception filters applied.',
  },
  {
    id: 'job-1041',
    startedAt: '2026-03-26T05:18:00Z',
    finishedAt: '2026-03-26T05:20:48Z',
    status: 'partial',
    totalSources: 5,
    succeededSources: 4,
    discrepancies: 25,
    note: 'HPE Alletra endpoint timed out but partial snapshot preserved.',
  },
];

export const discrepancies: DiscrepancyRecord[] = [
  {
    id: 'disc-1',
    objectType: 'vm',
    identifier: 'APP-DB-01',
    sourceSystem: 'vcenter1',
    type: 'field_mismatch',
    field: 'powerState',
    itopValue: 'poweredOff',
    sourceValue: 'poweredOn',
    severity: 'high',
    summary: 'VM power state differs between iTop and vCenter.',
    createdAt: '2026-03-27T05:22:03Z',
  },
  {
    id: 'disc-2',
    objectType: 'host',
    identifier: 'esx-prod-08',
    sourceSystem: 'vcenter1',
    type: 'missing_in_itop',
    severity: 'medium',
    summary: 'Host exists in vCenter but is missing from iTop.',
    createdAt: '2026-03-27T05:22:11Z',
  },
  {
    id: 'disc-3',
    objectType: 'lun',
    identifier: 'naa.600508b1001c4d0f',
    sourceSystem: 'unity600',
    type: 'extra_in_itop',
    severity: 'low',
    summary: 'LUN still exists in iTop after decommission in source.',
    createdAt: '2026-03-27T05:22:33Z',
  },
  {
    id: 'disc-4',
    objectType: 'vm',
    identifier: 'QA-LOAD-02',
    sourceSystem: 'pure1',
    type: 'field_mismatch',
    field: 'vDisk',
    itopValue: '200 GB',
    sourceValue: '240 GB',
    severity: 'medium',
    summary: 'VM storage size does not match snapshot.',
    createdAt: '2026-03-27T05:22:53Z',
  },
];

export const exceptions: ExceptionRecord[] = [
  {
    id: 'exc-1',
    objectType: 'vm',
    identifier: 'TEMP-TEST-VM-01',
    sourceSystem: 'vcenter1',
    reason: 'VM test, not managed in CMDB.',
    createdBy: 'admin',
    createdAt: '2026-03-25T10:00:00Z',
    updatedAt: '2026-03-25T10:00:00Z',
  },
];
